name = "GeoSpatialTools"
uuid = "e5e1ad5e-ee0c-4b47-a4d0-6381f0613ef7"
authors = ["elwan"]
version = "1.0.0-DEV"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
SQLite = "0aa819cd-b072-5ff4-a722-6bc24af294d9"

[compat]
DataFrames = "1.7.0"
SQLite = "1.6.1"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
