name: CI

on:
  push:
    paths:
      - 'src/**'
  pull_request:
    paths:
      - 'src/**'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        julia-version: ['1.11']
        include:
          - os: windows-latest
            julia-version: '1.11'
            arch: x86
          - os: windows-latest
            julia-version: '1.11'
            arch: x64
          - os: ubuntu-latest
            julia-version: '1.11'
            arch: x64
          - os: macos-latest
            julia-version: '1.11'
            arch: x64

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.arch }}

      - name: Cache Julia packages
        uses: julia-actions/cache@v2

      - name: Install dependencies
        run: julia --project=. -e 'using Pkg; Pkg.instantiate()'

      - name: Run tests
        run: julia --project=. -e 'using Pkg; Pkg.test()'

